### ISSUE TITLE
Some problems with TBIntf

### ISSUE THREAD

**Issue by sjtutyx** [dlinknctu/OpenNet#114]
Actually, when I run the TBIntf-example, some confusing problems occur:
 *** ns-3 network demo
*** Creating Network
*** Configuring hosts
*** Error: moveIntf: tap0 not successfully moved to h0:
 RTNETLINK answers: File exists
*** Error: moveIntf: tap0 not successfully moved to h0:
 RTNETLINK answers: File exists
*** Error: moveIntf: tap0 not successfully moved to h0:
 RTNETLINK answers: File exists
*** Error: moveIntf: tap0 not successfully moved to h0:
 RTNETLINK answers: File exists
*** gave up after 3 retries

It seems there error are related to the cmd "ip link set" defined in util.py in mininet/mininet

My Mininet is 2.3.0d1 and NS3 version 3.26 (not the same with OpenNet)
Could anyone give me some suggestions?>? Many thanks~!

**Comment by kansokusha** [comment]
The error message shows that the network interface tap0 is already existing in namespace h0.

Before you try to execute the example script, did you build the OpenNet in your environment?
OpenNet has applyed many patches on Mininet and NS-3 to let them work together, one of the patch on Mininet is the procedure to remove network interfaces created by OpenNet script.

Since the integration relies on these patches, OpenNet only works on corresponding version of NS-3 and Mininet. Sorry for that we do not have resource to keep updating the version of Mininet and NS-3.

**Comment by sjtutyx** [comment]
Thank you for your help~
