### ISSUE TITLE
How to import the lte module in ns3 into opennet?

### ISSUE THREAD

**Issue by Lewin8687** [dlinknctu/OpenNet#81]
I have to use lte module in ns3 to simulate cellular network. Since ns3 is written in C, how to import corresponding parts like enodeb and ue? 

Thank you so much

**Comment by kansokusha** [comment]
Python binding makes NS-3 simulation scripts can be written in Python. 

    import ns.lte

The upper statement can import LTE module into the simulation script.

Since Mininet is based on Python and NS-3 supports Python binding, OpenNet uses Python as simulation scripting language. The installation flow of OpenNet includes install required components for NS-3 Python binding.

OpenNet provides the Python interface wrapper to make writing simulation script more easier. But currently only Wi-Fi has Python interface wrapper in OpenNet, we are planning to development a similar wrapper for LTE.

Writing LTE simulation script in Python is possible, but current OpenNet can not provide further support to make writing script easier.

**Comment by Lewin8687** [comment]
Alright, thank you so much, Kansokusha! I ll try it.

**Comment by Lewin8687** [comment]
Hi, lte module can be imported, but how can I add components like eNodeb? Should I still use mininet, for example "net = Mininet()"? 

Thank you!

**Comment by kansokusha** [comment]
Please refer NS-3 LTE [examples] (https://www.nsnam.org/docs/doxygen/dir_fdce2e2b9e210571394585f89b3f8594.html).
Mininet is not required, if your simulation scenario does not need to cooperate with OpenFlow.

LTE components (eNodeB, UE) in NS-3 are nodes which have LTE interfaces. These LTE interfaces are installed by LteHelper. The following examples indicate how to create node and LteHelper.
C++

    // ueNode
    NodeContainer ueContainer;
    ueContainer.Create (1);
    // LteHelper
    Ptr<LteHelper> lteHelper = CreateObject<LteHelper> (); 

Python

    # UE
    ueNode = ns.network.Node()
    # LteHelper
    lteHelper = ns.lte.LteHelper()

**Comment by Lewin8687** [comment]
Thank you for your response! I do need to work with OpenFlow, so Mininet is necessary. How to combine lte and mininet together? Create a mininet and add all components from lte?
Thank you

**Comment by kansokusha** [comment]
Yes, the main idea is to create a Mininet environment and put some LTE components into the environment. But the relationship between Mininet nodes and NS-3 nodes requires a little complicated manipulation.

We are exploring about how to integrating LTE and OpenFlow, sorry for we can not provide more detailed information.

**Comment by Lewin8687** [comment]
Ok, I see, thank you so much!
