### ISSUE TITLE
Tutorial and/or documentation

### ISSUE THREAD

**Issue by akhila-rao** [dlinknctu/OpenNet#92]
Hi, 
I am exploring OpenNet and would like to know if there are any documentations or tutorials for OpenNet ? Since OpenNet is a combination of mininet and ns3 would I be able to set-up emulations using mininet tutorials ? Do I need to learn any OpenNet specific commands or APIs before I can begin setting up emulations ?

**Comment by kansokusha** [comment]
Sorry, current OpenNet does not have documentations or tutorials.
But there are some references:
[Link modeling using NS-3](https://github.com/mininet/mininet/wiki/Link-modeling-using-ns-3)
[Example scripts](https://github.com/dlinknctu/OpenNet/tree/master/mininet-patch/examples/opennet)

To construct OpenNet emulation, understand Mininet via Mininet tutorial is very helpful.
If the emulation scenario need to adjust some Wi-Fi attributes, take a look at [NS-3 API](https://www.nsnam.org/docs/doxygen/index.html).
Since NS-3 supports Python binding, NS-3 API can be called in OpenNet emulation script.

**Comment by dside99** [comment]
Sorry, but the above link about example scripts doen't work.

**Comment by rascov** [comment]
I think it is moved to another repo: https://github.com/dlinknctu/mininet/tree/opennet/examples/opennet
